title = "gitleaks config"

[[rules]]
description = "Exclude specific file"
file = '''external-scripts/diat-barcode_pre-process/diat-barcode_v12.tsv'''
tags = ["genetic-sequence"]

[[rules]]
description = "Exclude specific file"
file = '''external-scripts/input_data/.*'''
tags = ["genetic-sequence"]