name: mozaiko

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11
  - pip
  - vsearch=2.13.3
  - cutadapt=4.9
  - catnip
  - numpy
  - pandas
  - matplotlib
  - biopython
  - tqdm
  - pyyaml
  - requests
  - wget
  - git