name: mozaiko

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11
  - pip
  - vsearch=2.16
  - cutadapt=4.9
  - catnip-seq
  - crabs=0.1.7
  - numpy
  - pandas
  - matplotlib
  - biopython
  - tqdm
  - pyyaml
  - requests
  - wget
  - git