#!/usr/bin/env python3

import argparse
from reference_database.sequence_import import CustomFastaImport
from reference_database.db_curation import CrabsScriptGenerator

def create_parser():
    parser = argparse.ArgumentParser(description="mosaiko: Piecing Together Complete Genetic Coverage for Biomonitoring")
    parser.add_argument('-i', '--input', required=True, help='Path to the input FASTA file')
    parser.add_argument('-o', '--output', help='Path to output files (for FASTA and CSV)')
    parser.add_argument('--csv', action='store_true', help='Generate CSV output')
    parser.add_argument('--assign_tax', action='store_true', help='Assign taxonomic information.')
    parser.add_argument('--dereplicate', action='store_true', help='Dereplicate sequences.')
    return parser

def main(): # Check and improve orchestration of the functions
    parser = create_parser()
    args = parser.parse_args()

    print("Initiating custom sequence import...")
    fasta_import = CustomFastaImport()
    fasta_import.read_fasta(args.input)

    if args.output:
        fasta_import.df2fasta(args.output)

    if args.csv:
        csv_output = args.output.rsplit('.', 1)[0] + '.csv' if args.output else 'processed_input_fasta.csv'
        fasta_import.df2csv(csv_output)

    crabs_generator = CrabsScriptGenerator()

    if args.assign_tax:
        crabs_generator.run_assign_tax_command()

    print(f"Processed {fasta_import.get_number_of_sequences()} sequences.")

if __name__ == "__main__":
    main()