name: Test Conda Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12
        auto-update-conda: true
        activate-environment: myenv
        environment-file: environment.yml

    - name: Initialize Conda
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda init bash
        conda config --set always_yes yes --set changeps1 no

    - name: Install package
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate myenv
        pip install .
      shell: bash

    - name: Run tests
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate myenv
        pytest
      shell: bash